### ISSUE TITLE
Best Practice?

### ISSUE THREAD

**Issue by IrealiTY** [mikevb1/TrialsCheeser#2]
Is there a best practice method for this tool?
We tried it and barely got matches, worked once and thats it

**Comment by sgtlaggy** [comment]
This tool doesn't give you a better chance of matching together, it just lets you know when you *are* matched together. This also applies to using Wireshark.

**Comment by IrealiTY** [comment]
Yep yep I understand that :) Sorry if I was unclear.
We just had Yellow and Greenlights come up extremely rarely.

Do you know if there still chances to be matched after a team has wins on a card?

**Comment by sgtlaggy** [comment]
You will match together at the same frequency whether anyone has wins or not.

The yellow light is really only for hosts to worry about, as it shows that the groups are communicating in the queue (basically hosts are determining whether or not to start the game). If you were host and getting those rarely, the hosts were probably not located close enough to narrow down the matchmaking region.
