### ISSUE TITLE
TrialsCheeser.

### ISSUE THREAD

**Issue by DestinyLoser** [mikevb1/TrialsCheeser#6]
I've been trying to cheese trials with some friends by matchmaking and tried using the app but I'm not sure if it needs to be updated since it's old and it doesn't seem to be working at all when we manage to matchmake together.

**Comment by sgtlaggy** [comment]
As far as I know, the way this app detects connections was fixed either before or with Beyond Light.
I don't play D2 anymore, nor do I really have any desire to keep it updated.
